swagger: "2.0"
info:
  description: "protected-api-service-{{envName}}"
  title: "protected-api-service-{{envName}}"
  version: "1.0.0"
host: "protected-api-service-{{envName}}.endpoints.tuup-servers.cloud.goog"
schemes:
  - "http"
paths:
  '/orders/v1/orders/{id}/externalRefund':
    post:
      operationId: public
      security:
        - auth0_jwk: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Public
          schema:
            type: string
        '400':
          description: Public
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Public
          schema:
            $ref: '#/definitions/Error'
        '403':
          description: Public
          schema:
            $ref: '#/definitions/Error'
securityDefinitions:
  auth0_jwk:
    authorizationUrl: "http://kyyti.com"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://kyyti.eu.auth0.com/"
    x-google-jwks_uri: "https://kyyti.eu.auth0.com/.well-known/jwks.json"
    x-google-audiences: "https://partner-api.kyyti.com"
definitions:
  Error:
    type: object
    properties:
      errorCode:
        type: string
      errorName:
        type: string
      extraInfo:
        type: object
      message:
        type: string
      devMessage:
        type: string
      stack:
        type: string
      cause:
        type: object
      nested:
        type: object
